# DATA COLLECTION

## HotPotQA dataset

In [3]:
import pandas as pd
import numpy as np
import os
import dotenv
from huggingface_hub import login
from datasets import load_dataset

In [4]:
# Load environment variables
dotenv.load_dotenv()
HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")

In [36]:
# Huggung Face login
login(token=HUGGINGFACEHUB_API_TOKEN)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [37]:
# load HotpotQA dataset chia batch
dataset = load_dataset("hotpot_qa", "distractor", streaming=True, batch_size=1000)

c:\Users\vnpq2\anaconda3\envs\min_ds-env\lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\vnpq2\.cache\huggingface\hub\datasets--hotpot_qa. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [38]:
ds["train"][0]

{'id': '5a7a06935542990198eaf050',
 'question': "Which magazine was started first Arthur's Magazine or First for Women?",
 'answer': "Arthur's Magazine",
 'type': 'comparison',
 'level': 'medium',
 'supporting_facts': {'title': ["Arthur's Magazine", 'First for Women'],
  'sent_id': [0, 0]},
 'context': {'title': ['Radio City (Indian radio station)',
   'History of Albanian football',
   'Echosmith',
   "Women's colleges in the Southern United States",
   'First Arthur County Courthouse and Jail',
   "Arthur's Magazine",
   '2014–15 Ukrainian Hockey Championship',
   'First for Women',
   'Freeway Complex Fire',
   'William Rast'],
  'sentences': [["Radio City is India's first private FM radio station and was started on 3 July 2001.",
    ' It broadcasts on 91.1 (earlier 91.0 in most cities) megahertz from Mumbai (where it was started in 2004), Bengaluru (started first in 2001), Lucknow and New Delhi (since 2003).',
    ' It plays Hindi, English and regional songs.',
    ' It was launched in Hyderabad in March 2006, in Chennai on 7 July 2006 and in Visakhapatnam October 2007.',
    ' Radio City recently forayed into New Media in May 2008 with the launch of a music portal - PlanetRadiocity.com that offers music related news, videos, songs, and other music-related features.',
    ' The Radio station currently plays a mix of Hindi and Regional music.',
    ' Abraham Thomas is the CEO of the company.'],
   ['Football in Albania existed before the Albanian Football Federation (FSHF) was created.',
    " This was evidenced by the team's registration at the Balkan Cup tournament during 1929-1931, which started in 1929 (although Albania eventually had pressure from the teams because of competition, competition started first and was strong enough in the duels) .",
    ' Albanian National Team was founded on June 6, 1930, but Albania had to wait 16 years to play its first international match and then defeated Yugoslavia in 1946.',
    ' In 1932, Albania joined FIFA (during the 12–16 June convention ) And in 1954 she was one of the founding members of UEFA.'],
   ['Echosmith is an American, Corporate indie pop band formed in February 2009 in Chino, California.',
    ' Originally formed as a quartet of siblings, the band currently consists of Sydney, Noah and Graham Sierota, following the departure of eldest sibling Jamie in late 2016.',
    ' Echosmith started first as "Ready Set Go!"',
    ' until they signed to Warner Bros.',
    ' Records in May 2012.',
    ' They are best known for their hit song "Cool Kids", which reached number 13 on the "Billboard" Hot 100 and was certified double platinum by the RIAA with over 1,200,000 sales in the United States and also double platinum by ARIA in Australia.',
    ' The song was Warner Bros.',
    " Records' fifth-biggest-selling-digital song of 2014, with 1.3 million downloads sold.",
    ' The band\'s debut album, "Talking Dreams", was released on October 8, 2013.'],
   ["Women's colleges in the Southern United States refers to undergraduate, bachelor's degree–granting institutions, often liberal arts colleges, whose student populations consist exclusively or almost exclusively of women, located in the Southern United States.",
    " Many started first as girls' seminaries or academies.",
    ' Salem College is the oldest female educational institution in the South and Wesleyan College is the first that was established specifically as a college for women.',
    ' Some schools, such as Mary Baldwin University and Salem College, offer coeducational courses at the graduate level.'],
   ['The First Arthur County Courthouse and Jail, was perhaps the smallest court house in the United States, and serves now as a museum.'],
   ["Arthur's Magazine (1844–1846) was an American literary periodical published in Philadelphia in the 19th century.",
    ' Edited by T.S. Arthur, it featured work by Edgar A. Poe, J.H. Ingraham, Sarah Josepha Hale, Thomas G. Spear, and others.',
    ' In May 1846 it was merged into "Godey\'s Lady\'s Book".'],
   ['The 2014–15 Ukrainian Hockey Championship was the 23rd season of the Ukrainian Hockey Championship.',
    ' Only four teams participated in the league this season, because of the instability in Ukraine and that most of the clubs had economical issues.',
    ' Generals Kiev was the only team that participated in the league the previous season, and the season started first after the year-end of 2014.',
    ' The regular season included just 12 rounds, where all the teams went to the semifinals.',
    ' In the final, ATEK Kiev defeated the regular season winner HK Kremenchuk.'],
   ["First for Women is a woman's magazine published by Bauer Media Group in the USA.",
    ' The magazine was started in 1989.',
    ' It is based in Englewood Cliffs, New Jersey.',
    ' In 2011 the circulation of the magazine was 1,310,696 copies.'],
   ['The Freeway Complex Fire was a 2008 wildfire in the Santa Ana Canyon area of Orange County, California.',
    ' The fire started as two separate fires on November 15, 2008.',
    ' The "Freeway Fire" started first shortly after 9am with the "Landfill Fire" igniting approximately 2 hours later.',
    ' These two separate fires merged a day later and ultimately destroyed 314 residences in Anaheim Hills and Yorba Linda.'],
   ['William Rast is an American clothing line founded by Justin Timberlake and Trace Ayala.',
    ' It is most known for their premium jeans.',
    ' On October 17, 2006, Justin Timberlake and Trace Ayala put on their first fashion show to launch their new William Rast clothing line.',
    ' The label also produces other clothing items such as jackets and tops.',
    ' The company started first as a denim line, later evolving into a men’s and women’s clothing line.']]}}

In [39]:
# turn to pandas dataframe
train = pd.DataFrame(ds["train"])
valid = pd.DataFrame(ds["validation"])

Verbalizing answers:   0%|          | 1/7405 [02:12<273:17:27, 132.88s/answer]

In [40]:
train.head()

,id,question,answer,type,level,supporting_facts,context
0,5a7a06935542990198eaf050,Which magazine was started first Arthur's Maga...,Arthur's Magazine,comparison,medium,"{'title': ['Arthur's Magazine', 'First for Wom...",{'title': ['Radio City (Indian radio station)'...
1,5a879ab05542996e4f30887e,The Oberoi family is part of a hotel company t...,Delhi,bridge,medium,"{'title': ['Oberoi family', 'The Oberoi Group'...","{'title': ['Ritz-Carlton Jakarta', 'Oberoi fam..."
2,5a8d7341554299441c6b9fe5,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,bridge,hard,"{'title': ['Allie Goertz', 'Allie Goertz', 'Al...","{'title': ['Lisa Simpson', 'Marge Simpson', 'B..."
3,5a82171f5542990a1d231f4a,What nationality was James Henry Miller's wife?,American,bridge,medium,"{'title': ['Peggy Seeger', 'Peggy Seeger', 'Ew...","{'title': ['Moloch: or, This Gentile World', '..."
4,5a84dd955542997b5ce3ff79,Cadmium Chloride is slightly soluble in this c...,alcohol,bridge,medium,"{'title': ['Cadmium chloride', 'Ethanol'], 'se...","{'title': ['Cadmium chloride', 'Water blue', '..."

In [41]:
valid.head()

,id,question,answer,type,level,supporting_facts,context
0,5a8b57f25542995d1e6f1371,Were Scott Derrickson and Ed Wood of the same ...,yes,comparison,hard,"{'title': ['Scott Derrickson', 'Ed Wood'], 'se...","{'title': ['Ed Wood (film)', 'Scott Derrickson..."
1,5a8c7595554299585d9e36b6,What government position was held by the woman...,Chief of Protocol,bridge,hard,"{'title': ['Kiss and Tell (1945 film)', 'Shirl...","{'title': ['Meet Corliss Archer', 'Shirley Tem..."
2,5a85ea095542994775f606a8,"What science fantasy young adult series, told ...",Animorphs,bridge,hard,"{'title': ['The Hork-Bajir Chronicles', 'The H...","{'title': ['Andre Norton Award', 'Victoria Han..."
3,5adbf0a255429947ff17385a,Are the Laleli Mosque and Esma Sultan Mansion ...,no,comparison,hard,"{'title': ['Laleli Mosque', 'Esma Sultan Mansi...",{'title': ['Esma Sultan (daughter of Abdülaziz...
4,5a8e3ea95542995a26add48d,"The director of the romantic comedy ""Big Stone...","Greenwich Village, New York City",bridge,hard,"{'title': ['Big Stone Gap (film)', 'Adriana Tr...",{'title': ['Just Another Romantic Wrestling Co...

In [42]:
# check the folder data/hotpot_qa2/ exists, if not create it
if not os.path.exists("../data/hotpot_qa/"):
    os.makedirs("../data/hotpot_qa/")

In [43]:
valid.to_csv("../data/hotpot_qa/valid.csv", index=False, encoding='utf-8-sig')
train.to_csv("../data/hotpot_qa/train.csv", index=False, encoding='utf-8-sig')